name: Swift

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: ./build.sh
    - name: Zip
      run: zip -r Ghidra.app.zip Ghidra.app
    - uses: actions/upload-artifact@v2
      with:
       name: my-artifact
       path: Ghidra.app.zip
